spring:  h2:    console:      enabled: true      path: /h2-console    profiles:       active: local
  datasource:
    dbcp2:
      url: jdbc:h2:mem:test;MODE=MSSQLServer
#      url: jdbc:h2:mem:;MODE=MSSQLServer
      username: ren
      password: password
      driver-class-name: org.h2.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


server:
  port: 8080